export const mockMatches = [
  {
    id: "1",
    sport: "football" as const,
    homeTeam: {
      name: "Manchester City",
      logo: "/manchester-city-logo.jpg",
      score: 2,
    },
    awayTeam: {
      name: "Liverpool",
      logo: "/liverpool-logo.jpg",
      score: 1,
    },
    status: "live" as const,
    time: "45'",
    league: "Premier League",
  },
  {
    id: "2",
    sport: "cricket" as const,
    homeTeam: {
      name: "India",
      logo: "/india-cricket-team.jpg",
      score: 285,
      wickets: 8,
    },
    awayTeam: {
      name: "Australia",
      logo: "/australia-cricket-team.jpg",
      score: 245,
      wickets: 7,
    },
    status: "live" as const,
    time: "80 overs",
    league: "ODI Series",
  },
  {
    id: "3",
    sport: "football" as const,
    homeTeam: {
      name: "Real Madrid",
      logo: "/real-madrid-logo.jpg",
      score: 3,
    },
    awayTeam: {
      name: "PSG",
      logo: "/psg-logo.jpg",
      score: 2,
    },
    status: "finished" as const,
    time: "Full Time",
    league: "Champions League",
  },
  {
    id: "4",
    sport: "cricket" as const,
    homeTeam: {
      name: "Mumbai Indians",
      logo: "/mumbai-indians.jpg",
      score: 156,
      wickets: 5,
    },
    awayTeam: {
      name: "Chennai Super Kings",
      logo: "/csk.jpg",
      score: 0,
      wickets: 0,
    },
    status: "upcoming" as const,
    time: "Today 7:30 PM",
    league: "IPL",
  },
]

export const mockNews = [
  {
    id: "1",
    title: "Manchester City Dominates Liverpool in Thrilling Derby",
    excerpt: "City's attacking prowess shines through as they secure three crucial points in the Premier League.",
    image: "/football-match-action.jpg",
    category: "Football",
    date: "Nov 9, 2025",
    readTime: "4 min",
  },
  {
    id: "2",
    title: "India's Batting Masterclass Against Australia",
    excerpt: "A spectacular century from the opening batsman leads India to a commanding position in the ODI series.",
    image: "/cricket-batting.jpg",
    category: "Cricket",
    date: "Nov 8, 2025",
    readTime: "5 min",
  },
  {
    id: "3",
    title: "Real Madrid's Champions League Journey Continues",
    excerpt: "The Spanish giants edge past PSG in a nail-biting encounter in Paris.",
    image: "/champions-league.jpg",
    category: "Football",
    date: "Nov 7, 2025",
    readTime: "3 min",
  },
  {
    id: "4",
    title: "IPL Season Preview: Teams and Star Players",
    excerpt: "Get ready for the biggest cricket spectacle as franchises prepare for another exciting season.",
    image: "/ipl-cricket.jpg",
    category: "Cricket",
    date: "Nov 6, 2025",
    readTime: "6 min",
  },
]

export const mockPlayers = [
  {
    id: "1",
    name: "Virat Kohli",
    sport: "cricket",
    team: "India",
    role: "Batter",
    image: "/virat-kohli.jpg",
    stats: {
      matches: 285,
      runs: 13000,
      average: 47.5,
      centuries: 46,
    },
  },
  {
    id: "2",
    name: "Erling Haaland",
    sport: "football",
    team: "Manchester City",
    role: "Forward",
    image: "/erling-haaland.jpg",
    stats: {
      matches: 48,
      goals: 48,
      assists: 12,
      awards: "Player of the Year",
    },
  },
  {
    id: "3",
    name: "Jasprit Bumrah",
    sport: "cricket",
    team: "India",
    role: "Bowler",
    image: "/jasprit-bumrah.jpg",
    stats: {
      matches: 110,
      wickets: 215,
      average: 19.5,
      economy: 4.2,
    },
  },
  {
    id: "4",
    name: "Kylian Mbappé",
    sport: "football",
    team: "Real Madrid",
    role: "Forward",
    image: "/placeholder.svg?height=300&width=300",
    stats: {
      matches: 180,
      goals: 142,
      assists: 75,
      awards: "Top Scorer 2024",
    },
  },
]
